<?php
declare(strict_types=1);

// MixpanelFeatureFlagsManagement SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MixpanelFeatureFlagsManagementUtility::setRegistrar(function (MixpanelFeatureFlagsManagementUtility $u): void {
    $u->clean = [MixpanelFeatureFlagsManagementClean::class, 'call'];
    $u->done = [MixpanelFeatureFlagsManagementDone::class, 'call'];
    $u->make_error = [MixpanelFeatureFlagsManagementMakeError::class, 'call'];
    $u->feature_add = [MixpanelFeatureFlagsManagementFeatureAdd::class, 'call'];
    $u->feature_hook = [MixpanelFeatureFlagsManagementFeatureHook::class, 'call'];
    $u->feature_init = [MixpanelFeatureFlagsManagementFeatureInit::class, 'call'];
    $u->fetcher = [MixpanelFeatureFlagsManagementFetcher::class, 'call'];
    $u->make_fetch_def = [MixpanelFeatureFlagsManagementMakeFetchDef::class, 'call'];
    $u->make_context = [MixpanelFeatureFlagsManagementMakeContext::class, 'call'];
    $u->make_options = [MixpanelFeatureFlagsManagementMakeOptions::class, 'call'];
    $u->make_request = [MixpanelFeatureFlagsManagementMakeRequest::class, 'call'];
    $u->make_response = [MixpanelFeatureFlagsManagementMakeResponse::class, 'call'];
    $u->make_result = [MixpanelFeatureFlagsManagementMakeResult::class, 'call'];
    $u->make_point = [MixpanelFeatureFlagsManagementMakePoint::class, 'call'];
    $u->make_spec = [MixpanelFeatureFlagsManagementMakeSpec::class, 'call'];
    $u->make_url = [MixpanelFeatureFlagsManagementMakeUrl::class, 'call'];
    $u->param = [MixpanelFeatureFlagsManagementParam::class, 'call'];
    $u->prepare_auth = [MixpanelFeatureFlagsManagementPrepareAuth::class, 'call'];
    $u->prepare_body = [MixpanelFeatureFlagsManagementPrepareBody::class, 'call'];
    $u->prepare_headers = [MixpanelFeatureFlagsManagementPrepareHeaders::class, 'call'];
    $u->prepare_method = [MixpanelFeatureFlagsManagementPrepareMethod::class, 'call'];
    $u->prepare_params = [MixpanelFeatureFlagsManagementPrepareParams::class, 'call'];
    $u->prepare_path = [MixpanelFeatureFlagsManagementPreparePath::class, 'call'];
    $u->prepare_query = [MixpanelFeatureFlagsManagementPrepareQuery::class, 'call'];
    $u->graphql_body = [MixpanelFeatureFlagsManagementGraphql::class, 'body'];
    $u->graphql_errors = [MixpanelFeatureFlagsManagementGraphql::class, 'errors'];
    $u->result_basic = [MixpanelFeatureFlagsManagementResultBasic::class, 'call'];
    $u->result_body = [MixpanelFeatureFlagsManagementResultBody::class, 'call'];
    $u->result_headers = [MixpanelFeatureFlagsManagementResultHeaders::class, 'call'];
    $u->transform_request = [MixpanelFeatureFlagsManagementTransformRequest::class, 'call'];
    $u->transform_response = [MixpanelFeatureFlagsManagementTransformResponse::class, 'call'];
});
